### ISSUE TITLE
error: invalid temporary id

### ISSUE THREAD

**Issue by rdale1** [wbthomason/zotodo#1]
I'm getting the following error for the article "<i>Phenomenal</i> : An automatic open source library for 3D shoot architecture reconstruction and analysis for image-based plant phenotyping" 
(and other articles in general, including eg "A Compact Model for the Complex Plant Circadian Clock"). I'm able to find the files on disc.

![zotodo_error](https://user-images.githubusercontent.com/20452255/84184653-61eab280-aa53-11ea-8b30-bd0ed45fad5f.png)
![zotodo_error_2](https://user-images.githubusercontent.com/20452255/84184654-62834900-aa53-11ea-8ae7-5de79734ebf3.png)

**Comment by wbthomason** [comment]
Thanks! I might have figured out what's wrong - do you have the `from_zotero` label defined in your Todoist account? Sorry, I should make it clearer in the README that you need to define any labels you use for that configuration field yourself. Or make sure the plugin defines them for you...

**Comment by rdale1** [comment]
That works, thank you! I thought it was referring to projects I wanted to sort into, sorry about that!

**Comment by wbthomason** [comment]
Ah, glad to hear that worked! Sorry the docs weren't super clear. Incidentally, this motivated me to implement automatic creation of missing projects/labels, so this shouldn't be a problem again.

Thanks, and please let me know if you run into any other issues/find anything else in the docs confusing/etc.!
