### ISSUE TITLE
Link to PDF file

### ISSUE THREAD

**Issue by jdkoen** [wbthomason/zotodo#13]
Is there a way to have the ToDoist task link to the PDF file and open it (or, alternatively, to open to the Zotero item)? I've tried the tokens in a bunch of different combinations, but have not been able to get it to work.

**Comment by wbthomason** [comment]
You can use the `${select_uri}` key for this, but note that you'll need the `zotero://` protocol handler set up before this will work. Sorry that this was hard to find; the docs are effectively nonexistent.

**Comment by jdkoen** [comment]
Thanks for the help! Very much appreciated. Any advice/resources on setting up the `zotero://` protocol handler up on Mac OS? I've had no luck finding much on it that doesn't require using the terminal with `osascript`

**Comment by wbthomason** [comment]
Unfortunately I don't use MacOS (I've only set this up on Linux), but it looks like this might be what you want? https://superuser.com/questions/548119/how-do-i-configure-custom-url-handlers-on-os-x

That post is pretty old, but hopefully the interface hasn't changed all that much?

**Comment by jdkoen** [comment]
Thanks! This was helpful. Apparently, the protocol is already set up
without any additional stuff. Appreciate the help.

**Comment by wbthomason** [comment]
Ah, great! Glad to hear it's working for you.
