### ISSUE TITLE
Incompatible with Zotero 6.0-beta.1+c603753f.

### ISSUE THREAD

**Issue by wenyaoliu** [wbthomason/zotodo#25]
![image](https://user-images.githubusercontent.com/94808374/153305765-145c584a-8e70-4229-a161-943802d9b9c3.png)

Using the latest version of Zotero beta and failed to enable Zotodo.

**Comment by yaronhb** [comment]
I have the same problem

**Comment by tenglu0417** [comment]
Hi, the same problem here. It seems incompatible with the Zotero 6.0 version

**Comment by PoloWitty** [comment]
Hey, me too. I wonder whether the developer could update it. I think this is a very very important function for thesis manage tools.

**Comment by xiaodl813** [comment]
However, in the stable Zotero 6.0 this plugin is still incompatible :(
I'm trying to roll back to 5.x .......

**Comment by xiaodl813** [comment]
I fall to roll back to  Zotero 5.x, but I found a way to solve this issue temporarily. 👇
https://github.com/wbthomason/zotodo/issues/30

**Comment by wbthomason** [comment]
Hi all, sorry for taking a while to get to this. I'm trying to figure out *why* the plugin is incompatible with 6.0 - I haven't been able to find any more detailed information. I'll post here when I get something figured out.

**Comment by wbthomason** [comment]
This will be fixed as soon as I can get Travis CI credits to build the new release asset.

**Comment by wbthomason** [comment]
@xiaodl813 @PoloWitty @tenglu0417 @yaronbh @wenyaoliu This should be fixed with the release of v0.8.2 - please let me know if you continue to have issues, and thank you for your patience!

**Comment by yaronhb** [comment]
@wbthomason Thank you so much for fixing this! Much appreciated!
