### ISSUE TITLE
A temporary solution of incompatible of Zotodo

### ISSUE THREAD

**Issue by xiaodl813** [wbthomason/zotodo#30]
1. Open Edit→Preference
2. Open Advanced→Advanced Configuration→Config Editor
    * **NOTE: THIS IS A DANGEROUS OPERATION**
3. Add a boolean key named `extensions.checkCompatibility.6.0` and the value is `false`
4. Save and restart Zotero
This is a temporary solution, the key should be removed after the plugin fixed. By the way, update the plugin to compatible with Zotero 6.x is the best way. Hope the author of Zotodo have time to update this useful plugin!
-----
Anyway, is there anyone knows that why this plugin is incompatible with the 6.x version? Thx

**Comment by jeongeunpark18** [comment]
Third this! I am a big fan of this add-on and would appreciate it working again for Zotero 6 :) 👍

**Comment by wbthomason** [comment]
This should be fixed as of the release of v0.8.2. Please let me know if you still have issues!
