### ISSUE TITLE
support for sections

### ISSUE THREAD

**Issue by jrabensc** [wbthomason/zotodo#4]
Todoist supports section to structure tasks within projects: https://developer.todoist.com/sync/v8/#sections

It would be useful if we could define a project **and** a section for new tasks from Zotodo.

**Comment by wbthomason** [comment]
Good idea! This shouldn't be too hard to add.

**Comment by wbthomason** [comment]
This should be implemented in 492c5f7; please re-open if this doesn't work for you/isn't what you had in mind. Thanks!
