### ISSUE TITLE
Support for deep links

### ISSUE THREAD

**Issue by jrabensc** [wbthomason/zotodo#8]
Adding a deep link to Zotero (like zotero://select/library/items/F2K7NVMF) into a tasks' title or comment would be useful.

I did some research, Zotero seem to support deep links:

https://forums.zotero.org/discussion/24241/
https://forums.zotero.org/discussion/70213/links-from-other-tools-into-zotero
https://zoteromusings.wordpress.com/2013/04/23/zotero-item-uris-from-client/

**Comment by wbthomason** [comment]
Is this distinct from https://github.com/wbthomason/zotodo/issues/2 in that it includes more precise targets? If so, I wonder if you have thoughts on the set of targets that it would be useful to include?

**Comment by jrabensc** [comment]
Sorry, I did not notice this was already possible. Works perfectly here, thanks.

**Comment by wbthomason** [comment]
No worries! I'll go ahead and close the issue, but feel free to reopen it if you'd like a change to this feature, etc.
